import { PriceListInterface } from "./price-list.component";

export  const PRICELIST_DATA: PriceListInterface[] = [
    { pickUp: 'NLNG roundabout', dropOff: 'Bonny beach', price: 5000, promoPrice: 4000},
    { pickUp: 'NLNG roundabout', dropOff: 'Shell gate', price: 4000, promoPrice: 3000},
    { pickUp: 'NLNG roundabout', dropOff: 'Bonny roundabout', price: 4500, promoPrice: 2500},
    { pickUp: 'NLNG roundabout', dropOff: 'Wilbros junction', price: 3000, promoPrice: 2000},
    { pickUp: 'NLNG roundabout', dropOff: 'Finima Stadium', price: 3000, promoPrice: 2000},
    { pickUp: 'NLNG roundabout', dropOff: 'Workers village junction', price: 2000, promoPrice: 1500},
    { pickUp: 'NLNG roundabout', dropOff: 'Akiama junction', price: 3000, promoPrice: 2000},
    { pickUp: 'NLNG roundabout', dropOff: 'H-block', price: 2000, promoPrice: 1500},
    {pickUp: 'NLNG roundabout', dropOff: 'Pack and ride', price: 2500, promoPrice: 2000},
    { pickUp: 'Finima', dropOff: 'Bonny beach', price: 6000, promoPrice: 4000},
    { pickUp: 'Finima', dropOff: 'Shell gate', price: 5000, promoPrice: 3000},
    { pickUp: 'Finima', dropOff: 'Wilbros junction', price: 4000, promoPrice: 2000},
    { pickUp: 'Finima', dropOff: 'Bonny roundabout', price: 4500, promoPrice: 3500},
    { pickUp: 'Finima', dropOff: 'Workers village gate', price: 3000, promoPrice: 2000},
    { pickUp: 'Finima', dropOff: 'Workers village junction', price: 3000, promoPrice: 1800},
    { pickUp: 'Finima', dropOff: 'Akiama  junction', price: 3200, promoPrice: 2500},
    { pickUp: 'Finima', dropOff: 'H-block', price: 2500, promoPrice: 2000},
    { pickUp: 'Finima', dropOff: 'Pack and ride', price: 2800, promoPrice: 2200},
    { pickUp: 'Bonny beach', dropOff: 'Finima', price: 8000, promoPrice: 5000},
    { pickUp: 'Bonny beach', dropOff: 'NLNG roundabout', price: 5000, promoPrice: 3000},
    { pickUp: 'Bonny beach', dropOff: 'RA gate', price: 5000, promoPrice: 3000},
    { pickUp: 'Bonny beach', dropOff: 'Pack and ride', price: 6000, promoPrice: 4500},
    { pickUp: 'Bonny beach', dropOff: 'IA', price: 6000, promoPrice: 4500},
    { pickUp: 'Bonny beach', dropOff: 'Workers village gate', price: 3500, promoPrice: 4000},
    { pickUp: 'Bonny beach', dropOff: 'Workers village junction', price: 3500, promoPrice: 3500},
    { pickUp: 'Bonny beach', dropOff: 'Abalamabie (last bus stop)', price: 6500, promoPrice: 5000},
    { pickUp: 'Bonny beach', dropOff: 'Akiama junction', price: 4000, promoPrice: 3500},
    { pickUp: 'Bonny beach', dropOff: 'Water well 1, 2, 3, 4, and 5', price: 5500, promoPrice: 3600},
    { pickUp: 'Bonny beach', dropOff: 'Water well 6, 7, and 8', price: 6000, promoPrice: 4000},
    { pickUp: 'Bonny beach', dropOff: 'Uguede', price: 5000, promoPrice: 4000},
    { pickUp: 'Pack and ride', dropOff: 'Finima', price: 4000, promoPrice: 3000},
    { pickUp: 'Pack and ride', dropOff: 'RA gate', price: 2500, promoPrice: 2000},
    { pickUp: 'Pack and ride', dropOff: 'Wilbros junction', price: 4000, promoPrice: 3000},
    { pickUp: 'Pack and ride', dropOff: 'Shell gate', price: 4500, promoPrice: 4000},
    { pickUp: 'Pack and ride', dropOff: 'Akiama junction', price: 5000, promoPrice: 3800},
    { pickUp: 'Pack and ride', dropOff: 'Akiama junction', price: 4000, promoPrice: 2800},
    { pickUp: 'Pack and ride', dropOff: 'Bonny roundabout', price: 5000, promoPrice: 4000},
    { pickUp: 'Pack and ride', dropOff: 'Bonny beach', price: 6000, promoPrice: 5000},
    { pickUp: 'Pack and ride', dropOff: 'Abalamabie (last bus stop)', price: 6000, promoPrice: 5000},
  ];
